import type { ComponentType } from 'react';

export type ToolCategory = '格式化' | '编解码' | '文本' | '图片' | '安全' | '网络' | '开发' | '其他';

export interface ToolMeta {
  id: string;
  name: string;
  description: string;
  icon: string;
  iconClass: string;
  category: ToolCategory;
  path: string;
  component: () => Promise<{ default: ComponentType }>;
  keywords: string[];
  status: '可用' | '开发中';
  featured?: boolean;
  preview?: string;
}

export const tools: ToolMeta[] = [
  {
    id: 'regex',
    name: '正则验证器',
    description: '实时测试正则表达式，高亮匹配结果，支持捕获组查看和结构可视化',
    icon: '.*',
    iconClass: 'icon-violet',
    category: '文本',
    path: '/regex',
    component: () => import('./features/regex-tester'),
    keywords: ['regex', 'regexp', '正则', '匹配', 'pattern'],
    status: '可用',
    featured: true,
    preview: '/\\b[A-Z0-9._%+-]+@[A-Z0-9.-]+\\.[A-Z]{2,}\\b/gi\n→ 3 matches found',
  },
  {
    id: 'json',
    name: 'JSON 格式化',
    description: '格式化、压缩、验证 JSON 数据，支持语法高亮和错误定位',
    icon: '{ }',
    iconClass: 'icon-amber',
    category: '格式化',
    path: '/json',
    component: () => import('./features/json-formatter'),
    keywords: ['json', 'format', 'beautify', '格式化', '美化', '压缩'],
    status: '可用',
    featured: true,
    preview: '{"name":"devkit","version":"1.0.0","tools":["json","regex"]}\n→ 4 keys, 128 chars',
  },
  {
    id: 'totp',
    name: '2FA 验证码',
    description: '基于 TOTP 协议生成二步验证码，支持密钥导入和隐私保护',
    icon: '2FA',
    iconClass: 'icon-green',
    category: '安全',
    path: '/totp',
    component: () => import('./features/totp'),
    keywords: ['2fa', 'totp', 'otp', '验证码', 'authenticator'],
    status: '可用',
  },
  {
    id: 'timestamp',
    name: '时间戳转换',
    description: 'Unix 时间戳与日期互转，支持秒/毫秒、多时区',
    icon: 'T/S',
    iconClass: 'icon-cyan',
    category: '格式化',
    path: '/timestamp',
    component: () => import('./features/timestamp-converter'),
    keywords: ['timestamp', 'unix', '时间戳', '日期', 'date'],
    status: '可用',
  },
  {
    id: 'base64',
    name: 'Base64/Base32 编解码',
    description: '文本的 Base64/Base32 编解码，支持 URL-safe 格式',
    icon: 'B64',
    iconClass: 'icon-amber',
    category: '编解码',
    path: '/base64',
    component: () => import('./features/base64-codec'),
    keywords: ['base64', 'encode', 'decode', '编解码'],
    status: '可用',
  },
  {
    id: 'url',
    name: 'URL 编解码',
    description: 'URL 编码/解码，参数解析表格，嵌套编码处理',
    icon: '%',
    iconClass: 'icon-green',
    category: '编解码',
    path: '/url',
    component: () => import('./features/url-codec'),
    keywords: ['url', 'encode', 'decode', '编解码', '参数'],
    status: '可用',
  },
  {
    id: 'diff',
    name: '文本 Diff 对比',
    description: '行级/字符级差异对比，支持并排和内联视图',
    icon: '<>',
    iconClass: 'icon-violet',
    category: '文本',
    path: '/diff',
    component: () => import('./features/diff-viewer'),
    keywords: ['diff', 'compare', '对比', '差异'],
    status: '可用',
  },
  {
    id: 'hash',
    name: 'Hash 生成器',
    description: 'MD5/SHA-1/SHA-256/SHA-512 哈希计算和对比',
    icon: '#',
    iconClass: 'icon-red',
    category: '安全',
    path: '/hash',
    component: () => import('./features/hash-generator'),
    keywords: ['hash', 'md5', 'sha', '哈希', '摘要'],
    status: '可用',
  },
  {
    id: 'color',
    name: '颜色格式转换',
    description: 'HEX/RGB/HSL/oklch 互转，颜色选择器，对比度检查',
    icon: 'RGB',
    iconClass: 'icon-amber',
    category: '图片',
    path: '/color',
    component: () => import('./features/color-converter'),
    keywords: ['color', 'hex', 'rgb', 'hsl', '颜色'],
    status: '可用',
  },
  {
    id: 'jwt',
    name: 'JWT 解析器',
    description: '解码 JWT Token，展示 Header/Payload/Signature',
    icon: 'JWT',
    iconClass: 'icon-green',
    category: '安全',
    path: '/jwt',
    component: () => import('./features/jwt-decoder'),
    keywords: ['jwt', 'token', 'json web token', '解析'],
    status: '可用',
  },
  {
    id: 'cron',
    name: 'Cron 表达式解析',
    description: 'Cron 表达式转自然语言，展示最近执行时间',
    icon: '* *',
    iconClass: 'icon-cyan',
    category: '开发',
    path: '/cron',
    component: () => import('./features/cron-parser'),
    keywords: ['cron', 'schedule', '定时', '计划任务'],
    status: '可用',
  },
  {
    id: 'markdown',
    name: 'Markdown 预览',
    description: '实时 Markdown 渲染预览，支持代码高亮',
    icon: 'MD',
    iconClass: 'icon-violet',
    category: '文本',
    path: '/markdown',
    component: () => import('./features/markdown-preview'),
    keywords: ['markdown', 'md', 'preview', '预览'],
    status: '可用',
  },
  {
    id: 'logs',
    name: '日志分析器',
    description: '粘贴日志后按级别、关键词筛选，快速定位问题',
    icon: '≡',
    iconClass: 'icon-cyan',
    category: '开发',
    path: '/logs',
    component: () => import('./features/log-analyzer'),
    keywords: ['log', 'analyze', '日志', '分析', '筛选'],
    status: '可用',
  },
  {
    id: 'translate',
    name: '快速翻译',
    description: '翻译代码注释、文档片段，支持多语言互译',
    icon: '文',
    iconClass: 'icon-red',
    category: '文本',
    path: '/translate',
    component: () => import('./features/translator'),
    keywords: ['translate', '翻译', 'i18n'],
    status: '可用',
  },
  {
    id: 'uuid',
    name: 'UUID 生成器',
    description: '生成 v4/v7 UUID，批量生成，自定义格式',
    icon: 'ID',
    iconClass: 'icon-green',
    category: '开发',
    path: '/uuid',
    component: () => import('./features/uuid-generator'),
    keywords: ['uuid', 'guid', 'unique', '生成'],
    status: '可用',
  },
  {
    id: 'qrcode',
    name: '二维码工具',
    description: '生成/解析二维码，支持8种主题样式、渐变色彩、Logo嵌入',
    icon: 'QR',
    iconClass: 'icon-cyan',
    category: '图片',
    path: '/qrcode',
    component: () => import('./features/qrcode-tool'),
    keywords: ['qr', 'qrcode', '二维码', '条形码', 'barcode', '生成', '解析'],
    status: '可用',
  },
  {
    id: 'adb',
    name: 'ADB 自动化',
    description: '常用 ADB 命令封装，设备管理、应用安装、日志抓取',
    icon: '<svg viewBox="0 0 24 24" fill="currentColor"><path d="M6 18c0 .55.45 1 1 1h1v3.5c0 .83.67 1.5 1.5 1.5s1.5-.67 1.5-1.5V19h2v3.5c0 .83.67 1.5 1.5 1.5s1.5-.67 1.5-1.5V19h1c.55 0 1-.45 1-1V8H6v10zM3.5 8C2.67 8 2 8.67 2 9.5v7c0 .83.67 1.5 1.5 1.5S5 17.33 5 16.5v-7C5 8.67 4.33 8 3.5 8zm17 0c-.83 0-1.5.67-1.5 1.5v7c0 .83.67 1.5 1.5 1.5s1.5-.67 1.5-1.5v-7c0-.83-.67-1.5-1.5-1.5zm-4.97-5.84l1.3-1.3c.2-.2.2-.51 0-.71-.2-.2-.51-.2-.71 0l-1.48 1.48A5.84 5.84 0 0 0 12 1c-.96 0-1.86.23-2.66.63L7.85.15c-.2-.2-.51-.2-.71 0-.2.2-.2.51 0 .71l1.31 1.31A5.983 5.983 0 0 0 6 7h12c0-2.12-1.1-3.98-2.47-4.84zM10 5H9V4h1v1zm5 0h-1V4h1v1z"/></svg>',
    iconClass: 'icon-amber',
    category: '开发',
    path: '/adb',
    component: () => import('./features/adb-tools'),
    keywords: ['adb', 'android', '设备', '自动化'],
    status: '可用',
  },
  {
    id: 'yaml',
    name: 'YAML 格式化',
    description: 'YAML 美化、压缩、验证，支持转 JSON',
    icon: 'YML',
    iconClass: 'icon-green',
    category: '格式化',
    path: '/yaml',
    component: () => import('./features/yaml-formatter'),
    keywords: ['yaml', 'yml', 'format', '格式化', '美化', '压缩', 'k8s', 'docker'],
    status: '可用',
  },
  {
    id: 'password',
    name: '密码生成器',
    description: '可定制长度、字符集的安全密码批量生成',
    icon: '***',
    iconClass: 'icon-red',
    category: '安全',
    path: '/password',
    component: () => import('./features/password-generator'),
    keywords: ['password', 'generate', '密码', '生成', '安全', 'random'],
    status: '可用',
  },
  {
    id: 'imgCompress',
    name: '图片压缩',
    description: 'PNG/JPEG/WebP 图片有损压缩，支持质量调节和尺寸缩放',
    icon: 'IMG',
    iconClass: 'icon-amber',
    category: '图片',
    path: '/img-compress',
    component: () => import('./features/image-compressor'),
    keywords: ['image', 'compress', '图片', '压缩', 'jpeg', 'webp', 'png', 'quality'],
    status: '可用',
  },
  {
    id: 'imgConvert',
    name: '图片格式转换',
    description: 'PNG/JPEG/WebP 图片格式互转，支持质量调节',
    icon: '↔',
    iconClass: 'icon-green',
    category: '图片',
    path: '/img-convert',
    component: () => import('./features/image-converter'),
    keywords: ['image', 'convert', '图片', '转换', 'format', 'png', 'jpeg', 'webp'],
    status: '可用',
  },
  {
    id: 'jsonSchema',
    name: 'JSON Schema 验证器',
    description: '根据 JSON Schema 校验 JSON 数据，高亮错误位置',
    icon: '{}✓',
    iconClass: 'icon-amber',
    category: '格式化',
    path: '/json-schema',
    component: () => import('./features/json-schema-validator'),
    keywords: ['json', 'schema', 'validate', '验证', '校验', 'api'],
    status: '可用',
  },
  {
    id: 'jsonCsv',
    name: 'JSON ↔ CSV 转换',
    description: 'JSON 数组与 CSV 双向转换，支持自定义分隔符和嵌套展开',
    icon: '{},',
    iconClass: 'icon-green',
    category: '格式化',
    path: '/json-csv',
    component: () => import('./features/json-csv-converter'),
    keywords: ['json', 'csv', '转换', 'convert', '数据', 'excel'],
    status: '可用',
  },
  {
    id: 'xml',
    name: 'XML 格式化',
    description: 'XML 美化、压缩、转 JSON',
    icon: '</>',
    iconClass: 'icon-violet',
    category: '格式化',
    path: '/xml',
    component: () => import('./features/xml-formatter'),
    keywords: ['xml', 'format', '格式化', '美化', 'json', 'soap'],
    status: '可用',
  },
  {
    id: 'toml',
    name: 'TOML 格式化',
    description: 'TOML 格式化、验证、转 JSON',
    icon: 'TML',
    iconClass: 'icon-amber',
    category: '格式化',
    path: '/toml',
    component: () => import('./features/toml-formatter'),
    keywords: ['toml', 'format', '格式化', 'rust', 'cargo', 'pyproject'],
    status: '可用',
  },
  {
    id: 'sql',
    name: 'SQL 格式化',
    description: 'SQL 语句美化、压缩，支持关键字高亮',
    icon: 'SQL',
    iconClass: 'icon-green',
    category: '格式化',
    path: '/sql',
    component: () => import('./features/sql-formatter'),
    keywords: ['sql', 'format', '格式化', '美化', 'query', 'database'],
    status: '可用',
  },
  {
    id: 'tokenCounter',
    name: 'Token 计数器',
    description: '估算文本 Token 数量和 API 调用成本',
    icon: '#T',
    iconClass: 'icon-violet',
    category: '开发',
    path: '/token-count',
    component: () => import('./features/token-counter'),
    keywords: ['token', 'count', 'llm', 'gpt', 'claude', 'ai', '成本'],
    status: '可用',
  },
  {
    id: 'tsType',
    name: 'TypeScript 类型生成',
    description: '从 JSON 数据自动生成 TypeScript 接口定义',
    icon: 'TS',
    iconClass: 'icon-cyan',
    category: '开发',
    path: '/ts-type',
    component: () => import('./features/ts-type-gen'),
    keywords: ['typescript', 'type', 'interface', 'json', '生成', '类型'],
    status: '可用',
  },
  {
    id: 'dns',
    name: 'DNS 查询',
    description: '查询域名的 A/AAAA/MX/CNAME/TXT/NS 等 DNS 记录（Google DNS-over-HTTPS）',
    icon: 'DNS',
    iconClass: 'icon-green',
    category: '网络',
    path: '/dns',
    component: () => import('./features/dns-lookup'),
    keywords: ['dns', 'lookup', '域名', '解析', 'mx', 'cname', 'record'],
    status: '可用',
  },
  {
    id: 'whois',
    name: 'WHOIS 查询',
    description: '查询域名注册信息、到期时间、注册商（RDAP 协议）',
    icon: '🔍',
    iconClass: 'icon-amber',
    category: '网络',
    path: '/whois',
    component: () => import('./features/whois-lookup'),
    keywords: ['whois', 'rdap', '域名', '注册', '查询', '到期'],
    status: '可用',
  },
  {
    id: 'ipLookup',
    name: 'IP 归属地查询',
    description: '查询 IP 地理位置、运营商、时区等信息',
    icon: '🌍',
    iconClass: 'icon-cyan',
    category: '网络',
    path: '/ip',
    component: () => import('./features/ip-lookup'),
    keywords: ['ip', 'lookup', 'geo', '地理', '归属地', '查询', 'isp'],
    status: '可用',
  },
  {
    id: 'imgBase64',
    name: '图片 Base64',
    description: '图片与 Base64 互转，支持拖拽上传和多种输出格式',
    icon: '🖼',
    iconClass: 'icon-amber',
    category: '编解码',
    path: '/img-base64',
    component: () => import('./features/image-base64'),
    keywords: ['image', 'base64', '图片', '编码', 'datauri', '转换'],
    status: '可用',
  },
  {
    id: 'favicon',
    name: 'Favicon 生成器',
    description: '从文字/Emoji/图片生成多尺寸 Favicon，附带 HTML 引用代码',
    icon: '🌐',
    iconClass: 'icon-amber',
    category: '图片',
    path: '/favicon',
    component: () => import('./features/favicon-generator'),
    keywords: ['favicon', 'icon', 'pwa', 'apple-touch', '网站图标', '生成'],
    status: '可用',
  },
  {
    id: 'barcode',
    name: '条形码生成器',
    description: '支持 Code128/EAN-13/UPC 等多种条码格式，可导出 PNG/SVG',
    icon: '|||',
    iconClass: 'icon-amber',
    category: '图片',
    path: '/barcode',
    component: () => import('./features/barcode-generator'),
    keywords: ['barcode', '条形码', 'code128', 'ean', 'upc', '生成'],
    status: '可用',
  },
  {
    id: 'colorPalette',
    name: '色板生成器',
    description: '基于色彩和谐理论生成调色板，支持互补/类似/三色/单色等模式',
    icon: '🎨',
    iconClass: 'icon-amber',
    category: '图片',
    path: '/color-palette',
    component: () => import('./features/color-palette'),
    keywords: ['palette', 'color', '色板', '配色', '调色板', 'harmony'],
    status: '可用',
  },
  {
    id: 'textCipher',
    name: '文本加密/解密',
    description: '支持 ROT13/凯撒/盲文/颠倒字/零宽隐写等多种加密方式',
    icon: '🔐',
    iconClass: 'icon-green',
    category: '安全',
    path: '/text-cipher',
    component: () => import('./features/text-cipher'),
    keywords: ['cipher', 'encrypt', 'decrypt', '加密', '解密', 'rot13', 'morse', 'braille'],
    status: '可用',
  },
  {
    id: 'worldClock',
    name: '世界时钟',
    description: '全球主要城市实时时间，支持自定义城市列表',
    icon: '🌍',
    iconClass: 'icon-cyan',
    category: '其他',
    path: '/world-clock',
    component: () => import('./features/world-clock'),
    keywords: ['clock', 'time', 'timezone', '时钟', '时区', '世界时间'],
    status: '可用',
  },
  {
    id: 'baseConv',
    name: '进制转换器',
    description: '二进制/八进制/十进制/十六进制互转，支持分组显示',
    icon: '0x',
    iconClass: 'icon-amber',
    category: '格式化',
    path: '/base-convert',
    component: () => import('./features/base-converter'),
    keywords: ['base', 'convert', 'binary', 'hex', 'octal', 'decimal', '进制', '转换'],
    status: '可用',
  },
  {
    id: 'unicode',
    name: 'Unicode 编解码',
    description: 'Unicode 码点与字符互转，支持 \\uXXXX、U+XXXX、HTML Entity',
    icon: 'U+',
    iconClass: 'icon-violet',
    category: '编解码',
    path: '/unicode',
    component: () => import('./features/unicode-codec'),
    keywords: ['unicode', '编码', '解码', '码点', 'character', 'codepoint'],
    status: '可用',
  },
  {
    id: 'hex',
    name: 'Hex 编解码',
    description: '十六进制与文本/字节互转，支持 DEC/BIN 预览',
    icon: '0x',
    iconClass: 'icon-amber',
    category: '编解码',
    path: '/hex',
    component: () => import('./features/hex-codec'),
    keywords: ['hex', '十六进制', '编码', '解码', 'binary', 'byte'],
    status: '可用',
  },
  {
    id: 'htmlEntity',
    name: 'HTML Entity 编解码',
    description: 'HTML 实体与字符互转，支持命名实体和数字实体',
    icon: '&;',
    iconClass: 'icon-green',
    category: '编解码',
    path: '/html-entity',
    component: () => import('./features/html-entity-codec'),
    keywords: ['html', 'entity', '实体', '编码', '解码', 'xss'],
    status: '可用',
  },
  {
    id: 'mockGen',
    name: 'Mock API 生成器',
    description: '定义 API 端点生成 Mock 代码，支持批量生成测试数据',
    icon: '{}',
    iconClass: 'icon-amber',
    category: '开发',
    path: '/mock',
    component: () => import('./features/mock-generator'),
    keywords: ['mock', 'api', 'msw', 'json-server', 'fetch-mock', '测试', '数据', '模拟', '接口'],
    status: '可用',
  },
  {
    id: 'emoji',
    name: 'Emoji 搜索',
    description: 'Emoji 搜索与复制，支持中英文关键词和平台差异说明',
    icon: '😀',
    iconClass: 'icon-amber',
    category: '文本',
    path: '/emoji',
    component: () => import('./features/emoji-browser'),
    keywords: ['emoji', '表情', '符号', '搜索', '复制'],
    status: '可用',
  },
  {
    id: 'graphql',
    name: 'GraphQL 格式化',
    description: 'GraphQL query/mutation 美化、压缩',
    icon: 'GQL',
    iconClass: 'icon-violet',
    category: '格式化',
    path: '/graphql',
    component: () => import('./features/graphql-formatter'),
    keywords: ['graphql', 'gql', 'format', '格式化', 'query', 'mutation'],
    status: '可用',
  },
  {
    id: 'csvViewer',
    name: 'CSV 查看器',
    description: 'CSV 数据预览、排序、筛选，支持导出 JSON',
    icon: 'CSV',
    iconClass: 'icon-green',
    category: '文本',
    path: '/csv',
    component: () => import('./features/csv-viewer'),
    keywords: ['csv', 'viewer', '查看', '数据', '表格', 'excel'],
    status: '可用',
  },
  {
    id: 'textToolkit',
    name: '文本编辑工具',
    description: '大小写转换、排序/去重、批量替换、转义/反转义、对齐/表格化',
    icon: 'A≡',
    iconClass: 'icon-cyan',
    category: '文本',
    path: '/text-toolkit',
    component: () => import('./features/text-toolkit'),
    keywords: ['text', 'case', 'sort', 'replace', 'escape', 'align', '文本', '大小写', '排序', '替换', '转义', '对齐'],
    status: '可用',
  },
  {
    id: 'x509',
    name: 'X.509 证书解析',
    description: '解析 PEM 格式 SSL 证书，查看有效期、颁发者、版本等信息',
    icon: '🔒',
    iconClass: 'icon-green',
    category: '安全',
    path: '/x509',
    component: () => import('./features/x509-parser'),
    keywords: ['x509', 'ssl', 'certificate', 'cert', '证书', 'pem', '解析'],
    status: '可用',
  },
  {
    id: 'hmac',
    name: 'HMAC 计算器',
    description: 'HMAC-SHA1/256/384/512 带密钥哈希计算',
    icon: 'H#',
    iconClass: 'icon-amber',
    category: '安全',
    path: '/hmac',
    component: () => import('./features/hmac-calculator'),
    keywords: ['hmac', 'sha', 'hash', '密钥', '签名', 'api'],
    status: '可用',
  },
  {
    id: 'textStats',
    name: '文本统计',
    description: '字符数、词数、行数、段落数、阅读时间、字符频率分析',
    icon: '#',
    iconClass: 'icon-cyan',
    category: '文本',
    path: '/text-stats',
    component: () => import('./features/text-stats'),
    keywords: ['text', 'stats', 'count', '统计', '字数', '字符', '分析'],
    status: '可用',
  },
  {
    id: 'lorem',
    name: 'Lorem Ipsum 生成器',
    description: '生成占位文本，支持拉丁文和中文，可选段落/句子/词',
    icon: 'Li',
    iconClass: 'icon-amber',
    category: '文本',
    path: '/lorem',
    component: () => import('./features/lorem-generator'),
    keywords: ['lorem', 'ipsum', 'placeholder', '占位', '文本', '生成'],
    status: '可用',
  },
  {
    id: 'asciiArt',
    name: 'ASCII 艺术字',
    description: '文字转 ASCII Art，支持 6 种字体主题',
    icon: 'A',
    iconClass: 'icon-violet',
    category: '文本',
    path: '/ascii-art',
    component: () => import('./features/ascii-art'),
    keywords: ['ascii', 'art', 'text', 'font', '艺术字', '字体', '生成'],
    status: '可用',
  },
  {
    id: 'charRef',
    name: '字符对照表',
    description: 'ASCII/Unicode 码表速查，字符反查编码',
    icon: 'Aa',
    iconClass: 'icon-green',
    category: '文本',
    path: '/char-reference',
    component: () => import('./features/char-reference'),
    keywords: ['ascii', 'unicode', 'char', '字符', '码表', '编码'],
    status: '可用',
  },
  {
    id: 'travel',
    name: '去哪玩',
    description: '中国地图旅行路线规划，选择出发点和天数，推荐多条游玩路线',
    icon: '🗺️',
    iconClass: 'icon-green',
    category: '其他',
    path: '/travel',
    component: () => import('./features/travel-planner'),
    keywords: ['travel', 'trip', 'route', '旅行', '路线', '规划', '地图', '游玩'],
    status: '可用',
  },
  {
    id: 'addressGen',
    name: '地址生成器',
    description: '生成真实格式的各国/地区收货地址，含邮编、街道、城市',
    icon: '📍',
    iconClass: 'icon-green',
    category: '其他',
    path: '/address-gen',
    component: () => import('./features/address-generator'),
    keywords: ['address', 'generate', '地址', '生成', '邮编', '测试数据', 'fake'],
    status: '可用',
  },
  {
    id: 'unitConv',
    name: '单位换算器',
    description: '长度/重量/温度/存储/速度/面积等单位换算',
    icon: '⇄',
    iconClass: 'icon-green',
    category: '格式化',
    path: '/unit-convert',
    component: () => import('./features/unit-converter'),
    keywords: ['unit', 'convert', '单位', '换算', '长度', '重量', '温度'],
    status: '可用',
  },
  {
    id: 'terminal',
    name: '终端美化器',
    description: '终端输出数据美化，支持 16 种主题样式、语法高亮和导出',
    icon: '>_',
    iconClass: 'icon-green',
    category: '开发',
    path: '/terminal',
    component: () => import('./features/terminal-styler'),
    keywords: ['terminal', 'theme', '终端', '美化', '主题', 'shell', 'highlight', 'dracula', 'nord'],
    status: '可用',
  },
  {
    id: 'rss',
    name: 'RSS 工具',
    description: 'RSS/Atom 阅读器、生成器和验证器',
    icon: 'RSS',
    iconClass: 'icon-amber',
    category: '开发',
    path: '/rss',
    component: () => import('./features/rss-tool'),
    keywords: ['rss', 'atom', 'feed', 'xml', '阅读', '生成', '验证', '订阅'],
    status: '可用',
  },
  {
    id: 'chart',
    name: '图表生成器',
    description: '支持 12 种图表类型和 8 种主题，数据表格输入，导出 PNG',
    icon: '📊',
    iconClass: 'icon-amber',
    category: '图片',
    path: '/chart',
    component: () => import('./features/chart-generator'),
    keywords: ['chart', 'graph', '图表', '柱状图', '折线图', '饼图', '可视化', '数据'],
    status: '可用',
  },
  {
    id: 'slug',
    name: '文本转 Slug',
    description: '将文本转换为 URL 友好的 slug 格式',
    icon: '🔗',
    iconClass: 'icon-green',
    category: '文本',
    path: '/slug',
    component: () => import('./features/slug-generator'),
    keywords: ['slug', 'url', '文本', '转换', 'seo', '链接'],
    status: '可用',
  },
  {
    id: 'mime',
    name: 'MIME Type 查询',
    description: '查询常见 MIME 类型及其文件扩展名',
    icon: '📋',
    iconClass: 'icon-cyan',
    category: '开发',
    path: '/mime',
    component: () => import('./features/mime-lookup'),
    keywords: ['mime', 'type', 'content-type', '媒体类型', '文件类型'],
    status: '可用',
  },
  {
    id: 'httpStatus',
    name: 'HTTP 状态码',
    description: 'HTTP 状态码速查，含中英文说明和 RFC 引用',
    icon: '🌐',
    iconClass: 'icon-amber',
    category: '开发',
    path: '/http-status',
    component: () => import('./features/http-status'),
    keywords: ['http', 'status', 'code', '状态码', '404', '500'],
    status: '可用',
  },
  {
    id: 'ua',
    name: 'UA 解析器',
    description: '解析 User-Agent 字符串，识别浏览器、操作系统和设备',
    icon: '🔍',
    iconClass: 'icon-violet',
    category: '开发',
    path: '/ua-parser',
    component: () => import('./features/ua-parser'),
    keywords: ['ua', 'user-agent', 'browser', '浏览器', '解析', '设备'],
    status: '可用',
  },
  {
    id: 'watermark',
    name: '图片水印',
    description: '为图片添加文字水印，支持位置、透明度、旋转和平铺',
    icon: '💧',
    iconClass: 'icon-amber',
    category: '图片',
    path: '/watermark',
    component: () => import('./features/watermark-tool'),
    keywords: ['watermark', '水印', '图片', '文字', '保护', '版权'],
    status: '可用',
  },
  {
    id: 'privacy',
    name: '隐私协议生成器',
    description: '一键生成 APP 隐私政策和服务条款，覆盖主流应用市场审核要求',
    icon: '📜',
    iconClass: 'icon-green',
    category: '开发',
    path: '/privacy',
    component: () => import('./features/privacy-generator'),
    keywords: ['privacy', 'policy', 'terms', '隐私', '协议', '服务条款', '审核', 'app store'],
    status: '可用',
  },
  {
    id: 'license',
    name: '开源许可证生成器',
    description: '一键生成开源许可证文件，支持 MIT、Apache、GPL 等 10 种常见协议',
    icon: '⚖️',
    iconClass: 'icon-cyan',
    category: '开发',
    path: '/license',
    component: () => import('./features/license-generator'),
    keywords: ['license', 'mit', 'apache', 'gpl', '开源', '许可证', '协议', 'open source'],
    status: '可用',
  },
  {
    id: 'spinWheel',
    name: '随机转盘',
    description: '炫酷随机转盘，支持自定义主题和选项，帮你做随机决策',
    icon: '🎡',
    iconClass: 'icon-amber',
    category: '其他',
    path: '/spin-wheel',
    component: () => import('./features/spin-wheel'),
    keywords: ['spin', 'wheel', 'random', '转盘', '随机', '决策', '抽奖'],
    status: '可用',
  },
  {
    id: 'nameGen',
    name: '起名神器',
    description: '基于四书五经、诗词典故和历史人物字号，智能生成有文化内涵的名字',
    icon: '📜',
    iconClass: 'icon-amber',
    category: '其他',
    path: '/name-generator',
    component: () => import('./features/name-generator'),
    keywords: ['name', 'generator', '起名', '取名', '四书五经', '诗词', '古典', '文化'],
    status: '可用',
  },
  {
    id: 'currency',
    name: '货币汇率换算',
    description: '实时汇率查询与货币换算，支持 166 种货币，每 30 分钟自动刷新',
    icon: '💱',
    iconClass: 'icon-green',
    category: '其他',
    path: '/currency',
    component: () => import('./features/currency-converter'),
    keywords: ['currency', 'exchange', 'rate', '货币', '汇率', '换算', '美元', '欧元', '人民币'],
    status: '可用',
  },
  {
    id: 'disease',
    name: '传染病追踪',
    description: '实时追踪全球传染病疫情动态，来源 WHO 官方数据，含预防指南和物资准备清单',
    icon: '🦠',
    iconClass: 'icon-red',
    category: '其他',
    path: '/disease',
    component: () => import('./features/disease-tracker'),
    keywords: ['disease', 'outbreak', 'who', '传染病', '疫情', '追踪', '预防', 'covid', '流感'],
    status: '可用',
  },
  {
    id: 'websiteScreenshot',
    name: '网站截屏',
    description: '输入 URL 生成网页截图，支持主题背景和设备框架',
    icon: '📸',
    iconClass: 'icon-cyan',
    category: '图片',
    path: '/website-screenshot',
    component: () => import('./features/website-screenshot'),
    keywords: ['screenshot', 'website', 'url', '截屏', '截图', '网页', 'capture', 'screen'],
    status: '可用',
  },
];

export const categories: { id: string; label: string }[] = [
  { id: 'all', label: '全部' },
  { id: '格式化', label: '格式化' },
  { id: '编解码', label: '编解码' },
  { id: '文本', label: '文本' },
  { id: '图片', label: '图片' },
  { id: '安全', label: '安全' },
  { id: '网络', label: '网络' },
  { id: '开发', label: '开发' },
  { id: '其他', label: '其他' },
];
