import type { ComponentType } from 'react';

export type ToolCategory = '编码/解码' | '格式化/转换' | '安全/加密' | '文本处理' | '开发调试' | '系统工具';

export interface ToolMeta {
  id: string;
  name: string;
  description: string;
  icon: string;
  iconClass: string;
  category: ToolCategory;
  path: string;
  component: () => Promise<{ default: ComponentType }>;
  keywords: string[];
  status: '可用' | '开发中';
  featured?: boolean;
  preview?: string;
}

export const tools: ToolMeta[] = [
  {
    id: 'totp',
    name: '2FA 验证码',
    description: '基于 TOTP 协议生成二步验证码，支持密钥导入和隐私保护',
    icon: '⊛',
    iconClass: 'icon-green',
    category: '安全/加密',
    path: '/totp',
    component: () => import('./features/totp'),
    keywords: ['2fa', 'totp', 'otp', '验证码', 'authenticator'],
    status: '可用',
    featured: true,
  },
  {
    id: 'json',
    name: 'JSON 格式化',
    description: '格式化、压缩、验证 JSON 数据，支持语法高亮和错误定位',
    icon: '{ }',
    iconClass: 'icon-amber',
    category: '格式化/转换',
    path: '/json',
    component: () => import('./features/json-formatter'),
    keywords: ['json', 'format', 'beautify', '格式化', '美化', '压缩'],
    status: '可用',
    featured: true,
    preview: '{\n  "name": "devkit",\n  "version": "1.0.0",\n  "tools": ["json", "regex"]\n}',
  },
  {
    id: 'regex',
    name: '正则验证器',
    description: '实时测试正则表达式，高亮匹配结果，支持捕获组查看',
    icon: '.*',
    iconClass: 'icon-violet',
    category: '文本处理',
    path: '/regex',
    component: () => import('./features/regex-tester'),
    keywords: ['regex', 'regexp', '正则', '匹配', 'pattern'],
    status: '可用',
    featured: true,
    preview: '/\\b[A-Z0-9._%+-]+@[A-Z0-9.-]+\\.[A-Z]{2,}\\b/gi\n→ 3 matches found',
  },
  {
    id: 'timestamp',
    name: '时间戳转换',
    description: 'Unix 时间戳与日期互转，支持秒/毫秒、多时区',
    icon: '⏱',
    iconClass: 'icon-cyan',
    category: '格式化/转换',
    path: '/timestamp',
    component: () => import('./features/timestamp-converter'),
    keywords: ['timestamp', 'unix', '时间戳', '日期', 'date'],
    status: '开发中',
  },
  {
    id: 'base64',
    name: 'Base64 编解码',
    description: '文本和文件的 Base64 编解码，支持 URL-safe 格式',
    icon: 'B64',
    iconClass: 'icon-amber',
    category: '编码/解码',
    path: '/base64',
    component: () => import('./features/base64-codec'),
    keywords: ['base64', 'encode', 'decode', '编解码'],
    status: '开发中',
  },
  {
    id: 'url',
    name: 'URL 编解码',
    description: 'URL 编码/解码，参数解析表格，嵌套编码处理',
    icon: '%',
    iconClass: 'icon-green',
    category: '编码/解码',
    path: '/url',
    component: () => import('./features/url-codec'),
    keywords: ['url', 'encode', 'decode', '编解码', '参数'],
    status: '开发中',
  },
  {
    id: 'diff',
    name: '文本 Diff 对比',
    description: '行级/字符级差异对比，支持并排和内联视图',
    icon: '⇄',
    iconClass: 'icon-violet',
    category: '文本处理',
    path: '/diff',
    component: () => import('./features/diff-viewer'),
    keywords: ['diff', 'compare', '对比', '差异'],
    status: '开发中',
  },
  {
    id: 'hash',
    name: 'Hash 生成器',
    description: 'MD5/SHA-1/SHA-256/SHA-512 哈希计算和对比',
    icon: '#',
    iconClass: 'icon-red',
    category: '安全/加密',
    path: '/hash',
    component: () => import('./features/hash-generator'),
    keywords: ['hash', 'md5', 'sha', '哈希', '摘要'],
    status: '开发中',
  },
  {
    id: 'color',
    name: '颜色格式转换',
    description: 'HEX/RGB/HSL/oklch 互转，颜色选择器，对比度检查',
    icon: '🎨',
    iconClass: 'icon-amber',
    category: '格式化/转换',
    path: '/color',
    component: () => import('./features/color-converter'),
    keywords: ['color', 'hex', 'rgb', 'hsl', '颜色'],
    status: '开发中',
  },
  {
    id: 'jwt',
    name: 'JWT 解析器',
    description: '解码 JWT Token，展示 Header/Payload/Signature',
    icon: 'JWT',
    iconClass: 'icon-green',
    category: '安全/加密',
    path: '/jwt',
    component: () => import('./features/jwt-decoder'),
    keywords: ['jwt', 'token', 'json web token', '解析'],
    status: '开发中',
  },
  {
    id: 'cron',
    name: 'Cron 表达式解析',
    description: 'Cron 表达式转自然语言，展示最近执行时间',
    icon: '⏰',
    iconClass: 'icon-cyan',
    category: '开发调试',
    path: '/cron',
    component: () => import('./features/cron-parser'),
    keywords: ['cron', 'schedule', '定时', '计划任务'],
    status: '开发中',
  },
  {
    id: 'markdown',
    name: 'Markdown 预览',
    description: '实时 Markdown 渲染预览，支持代码高亮',
    icon: 'M↓',
    iconClass: 'icon-violet',
    category: '文本处理',
    path: '/markdown',
    component: () => import('./features/markdown-preview'),
    keywords: ['markdown', 'md', 'preview', '预览'],
    status: '开发中',
  },
  {
    id: 'logs',
    name: '日志分析器',
    description: '粘贴日志后按级别、关键词筛选，快速定位问题',
    icon: '≡',
    iconClass: 'icon-cyan',
    category: '开发调试',
    path: '/logs',
    component: () => import('./features/log-analyzer'),
    keywords: ['log', 'analyze', '日志', '分析', '筛选'],
    status: '开发中',
  },
  {
    id: 'translate',
    name: '快速翻译',
    description: '翻译代码注释、文档片段，支持多语言互译',
    icon: '文',
    iconClass: 'icon-red',
    category: '文本处理',
    path: '/translate',
    component: () => import('./features/translator'),
    keywords: ['translate', '翻译', 'i18n'],
    status: '开发中',
  },
  {
    id: 'uuid',
    name: 'UUID 生成器',
    description: '生成 v4/v7 UUID，批量生成，自定义格式',
    icon: 'ID',
    iconClass: 'icon-green',
    category: '开发调试',
    path: '/uuid',
    component: () => import('./features/uuid-generator'),
    keywords: ['uuid', 'guid', 'unique', '生成'],
    status: '开发中',
  },
  {
    id: 'adb',
    name: 'ADB 自动化',
    description: '常用 ADB 命令封装，设备管理、应用安装、日志抓取',
    icon: '⌘',
    iconClass: 'icon-amber',
    category: '系统工具',
    path: '/adb',
    component: () => import('./features/adb-tools'),
    keywords: ['adb', 'android', '设备', '自动化'],
    status: '开发中',
  },
];

export const categories: { id: string; label: string }[] = [
  { id: 'all', label: '全部' },
  { id: '格式化/转换', label: '格式化' },
  { id: '编码/解码', label: '编解码' },
  { id: '安全/加密', label: '安全' },
  { id: '文本处理', label: '文本' },
  { id: '开发调试', label: '调试' },
  { id: '系统工具', label: '系统' },
];
